### PR TITLE
Code workflow documentation

### PR DESCRIPTION
**Pull request by CurtisGreen**
Updated documentation to give a brief description of important files/classes as well as a table to show the call stack

### CODE REVIEW

**Review by EthanVieira — COMMENTED** [review]
Thoughts on putting this and some other stuff we have in the Readme in a different file? Like Contributors.md or something. I think this Readme should be more "customer facing".

**Comment by CurtisGreen** [comment]
> Thoughts on putting this and some other stuff we have in the Readme in a different file? Like Contributors.md or something. I think this Readme should be more "customer facing".

Could be good. I'll move it into the src folder with just a link from the main one. Also I just thought about it. Do you think a bullet list would be better than a table for the execution flow portion?

**Comment by CurtisGreen** [comment]
Alright moved it into src/ and added a link. Pretty interesting, I did it from rachel's computer and even though I logged in as myself it still says she made the commit 🤔

**Comment by EthanVieira** [comment]
> Could be good. I'll move it into the src folder with just a link from the main one. Also I just thought about it. Do you think a bullet list would be better than a table for the execution flow portion?

Table is fine

**Comment by EthanVieira** [comment]
> Alright moved it into src/ and added a link. Pretty interesting, I did it from rachel's computer and even though I logged in as myself it still says she made the commit 🤔

git config probably

**Review by EthanVieira — APPROVED** [review]

**Pull request merged**
